# permissions for end users to view gowebapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gowebapp-viewer-role
rules:
- apiGroups:
  - goweb.com
  resources:
  - gowebapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - goweb.com
  resources:
  - gowebapps/status
  verbs:
  - get
