# permissions for end users to edit gowebapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gowebapp-editor-role
rules:
- apiGroups:
  - goweb.com
  resources:
  - gowebapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goweb.com
  resources:
  - gowebapps/status
  verbs:
  - get
