apiVersion: goweb.com/v1alpha1
kind: GoWebApp
metadata:
  name: gowebapp-sample
spec:
  frontend:
    image: quay.io/yuvan/go-web
    imagePullSecrets: []
    replicaCount: 1
    service:
      port: 8080
      targetPort: 8080
      type: NodePort
