---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gowebapps.goweb.com
spec:
  group: goweb.com
  names:
    kind: GoWebApp
    listKind: GoWebAppList
    plural: gowebapps
    singular: gowebapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
